abstract class Constants {
  static double paddingApp = 40;
  static String splashImge = 'assets/images/splash.jpeg';
  static List<String> capitalCountry = <String>{
    'Cairo',
    'London',
    'Paris',
    'Kabul',
    'Tirana',
    'Algiers',
    'Luanda',
    'Yerevan',
    'Canberra',
    'Baku',
    'Manama',
    'Dhaka',
    'Minsk',
    'Brussels',
    'Brasilia',
    'Yaoundé',
    'Praia',
    'Beijing',
    'Djibouti',
    'Accra',
    'Baghdad',
    'Rome',
    'Tokyo',
    'Tripoli',
    'Islamabad',
    'Doha',
    'Lisbon',
    'Moscow',
    'Riyadh',
    'Madrid',
  }.toList();
}
